### ISSUE TITLE
A command line interface

### ISSUE THREAD

**Issue by ghost** [tarruda/node-xargs#1]
It would be nice if I could call `node-xargs` from my NPM/build scripts as a portable replacement for the `xargs` command... :)

**Comment by tarruda** [comment]
I'm not actively using this module, so it is unlikely that I will implement such feature in the near future. PRs are welcome though.

**Comment by tarruda** [comment]
An useful CLI would probably depend on more modules. For example, to implement the -0 option you can [split](https://www.npmjs.com/package/split). It is best to create a new npm module(eg: xargs-cli) that depends on this one(and possibly others to implement #2 and #3)
