### ISSUE TITLE
null option

### ISSUE THREAD

**Issue by ghost** [tarruda/node-xargs#3]
>  Useful when input items might contain white space, quote marks, or backslashes.

It would allow me to use it in combination with the output from `find ... -print0`.

**Comment by tarruda** [comment]
The xargs stream input is an array of lines, to use nul-separated streams, you can pass raw input through a stream like [split](https://github.com/dominictarr/split). Maybe something like this will work:

``` js
var xargs = require('xargs');
var split = require('split');

process.stdin
  .pipe(split(/\0/))
  .pipe(xargs([process.argv[2]].concat(process.argv.slice(3))))
  .pipe(process.stdout);
```
